# Generated by Django 2.2.8 on 2020-05-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=5000, verbose_name='Recado')),
                ('apelido_usuario', models.CharField(help_text='Pessoa que mandou a mensagem.', max_length=5000, verbose_name='Apelido')),
            ],
        ),
    ]
